name: zenfit
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # Firebase
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.4
  cloud_firestore: ^6.6.0

  # Authentication
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1

  # Date Format
  intl: ^0.20.2

  # chart
  fl_chart: ^1.0.0

   # Upload Foto
  image_picker: ^1.1.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png